export const ADD_TO_CART = 'ADD_TO_CART'
export const LOAD_CART = 'LOAD_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY'
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY'
export const EMPTY_CART = 'EMPTY_CART'

export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCT = 'GET_PRODUCT'
export const PRODUCT_ERROR = 'PRODUCT_ERROR'
export const ADD_PRODUCT = 'ADD_PRODUCT'
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'

export const ADD_COUPON = 'ADD_COUPON'
export const GET_COUPONS = 'GET_COUPONS'
export const DELETE_COUPON = 'DELETE_COUPON'
export const COUPON_ERROR = 'COUPON_ERROR'

export const CREATE_ORDER = 'CREATE_ORDER'
export const UPDATE_ORDER = 'UPDATE_ORDER'
export const UPDATE_SHIPPING_ADDRESS = 'UPDATE_SHIPPING_ADDRESS'
export const GET_ORDER = 'GET_ORDER'
export const GET_ORDERS = 'GET_ORDERS'
export const DELETE_ORDER = 'DELETE_ORDER'
export const ORDER_ERROR = 'ORDER_ERROR'

export const LOAD_USER = 'LOAD_USER'
export const GET_USERS = 'GET_USERS'
export const LOGIN = 'LOGIN'
export const REGISTER = 'REGISTER'
export const LOGOUT = 'LOGOUT'
export const DELETE_USER = 'DELETE_USER'
export const USER_ERROR = 'USER_ERROR'

export const ADD_ALERT = 'ADD_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
export const GET_ALERTS = 'GET_ALERTS'
export const ALERT_ERROR = 'ALERT_ERROR'
